# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Operations
  

    class AddPlaylistContentsMediaContainer < ::Crystalline::FieldAugmented
      extend T::Sig


      field :leaf_count_added, T.nilable(::Integer), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('leafCountAdded') } }

      field :leaf_count_requested, T.nilable(::Integer), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('leafCountRequested') } }

      field :metadata, T.nilable(T::Array[::PlexRubySDK::Operations::AddPlaylistContentsMetadata]), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('Metadata') } }

      field :size, T.nilable(::Integer), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('size') } }


      sig { params(leaf_count_added: T.nilable(::Integer), leaf_count_requested: T.nilable(::Integer), metadata: T.nilable(T::Array[::PlexRubySDK::Operations::AddPlaylistContentsMetadata]), size: T.nilable(::Integer)).void }
      def initialize(leaf_count_added: nil, leaf_count_requested: nil, metadata: nil, size: nil)
        @leaf_count_added = leaf_count_added
        @leaf_count_requested = leaf_count_requested
        @metadata = metadata
        @size = size
      end

      def ==(other)
        return false unless other.is_a? self.class
        return false unless @leaf_count_added == other.leaf_count_added
        return false unless @leaf_count_requested == other.leaf_count_requested
        return false unless @metadata == other.metadata
        return false unless @size == other.size
        true
      end
    end
  end
end
