# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Models
    module Operations
      DEFAULT_SUBTITLE_FORCED_SERVERS = [
        'https://plex.tv/api/v2'
      ].freeze
    
      # DefaultSubtitleForced - The forced subtitles searches mode (0 = Prefer non-forced subtitles, 1 = Prefer forced subtitles, 2 = Only show forced subtitles, 3 = Only show non-forced subtitles)
      class DefaultSubtitleForced < T::Enum
        enums do
          DISABLE = new(0)
          ENABLE = new(1)
        end
      end
    end
  end
end
