# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Operations
  

    class GetLibraryItemsSort < ::PlexRubySDK::Utils::FieldAugmented
      extend T::Sig


      field :default_direction, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('defaultDirection') } }

      field :key, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('key') } }

      field :title, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('title') } }

      field :default, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('default') } }

      field :desc_key, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('descKey') } }

      field :first_character_key, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('firstCharacterKey') } }


      sig { params(default_direction: ::String, key: ::String, title: ::String, default: T.nilable(::String), desc_key: T.nilable(::String), first_character_key: T.nilable(::String)).void }
      def initialize(default_direction: nil, key: nil, title: nil, default: nil, desc_key: nil, first_character_key: nil)
        @default_direction = default_direction
        @key = key
        @title = title
        @default = default
        @desc_key = desc_key
        @first_character_key = first_character_key
      end
    end
  end
end
