# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Models
    module Operations
    

      class GetSearchAllLibrariesDirector
        extend T::Sig
        include Crystalline::MetadataFields

        # Unique identifier for the director.
        field :id, ::Integer, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('id') } }
        # The role of Director
        field :tag, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('tag') } }
        # The absolute URL of the thumbnail image for the director.
        field :thumb, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('thumb') } }


        sig { params(id: ::Integer, tag: ::String, thumb: T.nilable(::String)).void }
        def initialize(id: nil, tag: nil, thumb: nil)
          @id = id
          @tag = tag
          @thumb = thumb
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @tag == other.tag
          return false unless @thumb == other.thumb
          true
        end
      end
    end
  end
end
