# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Operations
  

    class GetLibraryDetailsFilter < ::PlexRubySDK::Utils::FieldAugmented
      extend T::Sig


      field :filter, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('filter') } }

      field :filter_type, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('filterType') } }

      field :key, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('key') } }

      field :title, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('title') } }

      field :type, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('type') } }


      sig { params(filter: T.nilable(::String), filter_type: T.nilable(::String), key: T.nilable(::String), title: T.nilable(::String), type: T.nilable(::String)).void }
      def initialize(filter: nil, filter_type: nil, key: nil, title: nil, type: nil)
        @filter = filter
        @filter_type = filter_type
        @key = key
        @title = title
        @type = type
      end
    end
  end
end
