# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Operations
  

    class GetSearchAllLibrariesMediaContainer < ::Crystalline::FieldAugmented
      extend T::Sig


      field :search_result, T::Array[::PlexRubySDK::Operations::SearchResult], { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('SearchResult') } }

      field :size, ::Float, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('size') } }


      sig { params(search_result: T::Array[::PlexRubySDK::Operations::SearchResult], size: ::Float).void }
      def initialize(search_result: nil, size: nil)
        @search_result = search_result
        @size = size
      end

      def ==(other)
        return false unless other.is_a? self.class
        return false unless @search_result == other.search_result
        return false unless @size == other.size
        true
      end
    end
  end
end
