# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Operations
  

    class GetAllLibrariesDirectory < ::Crystalline::FieldAugmented
      extend T::Sig


      field :agent, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('agent') } }

      field :allow_sync, T::Boolean, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('allowSync') } }

      field :art, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('art') } }

      field :composite, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('composite') } }

      field :content, T::Boolean, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('content') } }
      # Unix epoch datetime in seconds
      field :content_changed_at, ::Integer, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('contentChangedAt') } }
      # Unix epoch datetime in seconds
      field :created_at, ::Integer, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('createdAt') } }

      field :directory, T::Boolean, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('directory') } }

      field :filters, T::Boolean, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('filters') } }

      field :hidden, ::Integer, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('hidden') } }

      field :key, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('key') } }

      field :language, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('language') } }

      field :location, T::Array[::PlexRubySDK::Operations::GetAllLibrariesLocation], { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('Location') } }

      field :refreshing, T::Boolean, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('refreshing') } }
      # Unix epoch datetime in seconds
      field :scanned_at, ::Integer, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('scannedAt') } }

      field :scanner, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('scanner') } }

      field :thumb, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('thumb') } }

      field :title, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('title') } }

      field :type, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('type') } }
      # Unix epoch datetime in seconds
      field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('updatedAt') } }

      field :uuid, ::String, { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('uuid') } }


      sig { params(agent: ::String, allow_sync: T::Boolean, art: ::String, composite: ::String, content: T::Boolean, content_changed_at: ::Integer, created_at: ::Integer, directory: T::Boolean, filters: T::Boolean, hidden: ::Integer, key: ::String, language: ::String, location: T::Array[::PlexRubySDK::Operations::GetAllLibrariesLocation], refreshing: T::Boolean, scanned_at: ::Integer, scanner: ::String, thumb: ::String, title: ::String, type: ::String, updated_at: ::Integer, uuid: ::String).void }
      def initialize(agent: nil, allow_sync: nil, art: nil, composite: nil, content: nil, content_changed_at: nil, created_at: nil, directory: nil, filters: nil, hidden: nil, key: nil, language: nil, location: nil, refreshing: nil, scanned_at: nil, scanner: nil, thumb: nil, title: nil, type: nil, updated_at: nil, uuid: nil)
        @agent = agent
        @allow_sync = allow_sync
        @art = art
        @composite = composite
        @content = content
        @content_changed_at = content_changed_at
        @created_at = created_at
        @directory = directory
        @filters = filters
        @hidden = hidden
        @key = key
        @language = language
        @location = location
        @refreshing = refreshing
        @scanned_at = scanned_at
        @scanner = scanner
        @thumb = thumb
        @title = title
        @type = type
        @updated_at = updated_at
        @uuid = uuid
      end
    end
  end
end
