# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Operations
  
    # GetLibraryItemsQueryParamIncludeMeta - Adds the Meta object to the response
    # 
    class GetLibraryItemsQueryParamIncludeMeta < T::Enum
      enums do
        DISABLE = new(0)
        ENABLE = new(1)
      end
    end
  end
end
