# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Operations
  

    class GetServerActivitiesMediaContainer < ::Crystalline::FieldAugmented
      extend T::Sig


      field :activity, T.nilable(T::Array[::PlexRubySDK::Operations::Activity]), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('Activity') } }

      field :size, T.nilable(::Float), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('size') } }


      sig { params(activity: T.nilable(T::Array[::PlexRubySDK::Operations::Activity]), size: T.nilable(::Float)).void }
      def initialize(activity: nil, size: nil)
        @activity = activity
        @size = size
      end
    end
  end
end
