# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Models
    module Operations
    

      class GetTopWatchedContentRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of media to retrieve or filter by.
        # 1 = movie
        # 2 = show
        # 3 = season
        # 4 = episode
        # E.g. A movie library will not return anything with type 3 as there are no seasons for movie libraries
        # 
        field :type, Models::Operations::GetTopWatchedContentQueryParamType, { 'query_param': { 'field_name': 'type', 'style': 'form', 'explode': true } }
        # Adds the Guid object to the response
        # 
        field :include_guids, T.nilable(Models::Operations::GetTopWatchedContentQueryParamIncludeGuids), { 'query_param': { 'field_name': 'includeGuids', 'style': 'form', 'explode': true } }


        sig { params(type: Models::Operations::GetTopWatchedContentQueryParamType, include_guids: T.nilable(Models::Operations::GetTopWatchedContentQueryParamIncludeGuids)).void }
        def initialize(type: nil, include_guids: nil)
          @type = type
          @include_guids = include_guids
        end

        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @include_guids == other.include_guids
          true
        end
      end
    end
  end
end
