# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module PlexRubySDK
  module Operations
  

    class Guids < ::PlexRubySDK::Utils::FieldAugmented
      extend T::Sig

      # The unique identifier for the Guid. Can be imdb://tt0286347, tmdb://1763, tvdb://2337
      # 
      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::PlexRubySDK::Utils.field_name('id') } }


      sig { params(id: T.nilable(::String)).void }
      def initialize(id: nil)
        @id = id
      end
    end
  end
end
