# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Operations

    class UpdatePlayProgressRequest < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # the media key
      field :key, String, { 'query_param': { 'field_name': 'key', 'style': 'form', 'explode': true } }
      # The playback state of the media item.
      field :state, String, { 'query_param': { 'field_name': 'state', 'style': 'form', 'explode': true } }
      # The time, in milliseconds, used to set the media playback progress.
      field :time, Float, { 'query_param': { 'field_name': 'time', 'style': 'form', 'explode': true } }


      sig { params(key: String, state: String, time: Float).void }
      def initialize(key: nil, state: nil, time: nil)
        @key = key
        @state = state
        @time = time
      end
    end


    class UpdatePlayProgressErrors < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :code, T.nilable(Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('code') } }

      field :message, T.nilable(String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('message') } }

      field :status, T.nilable(Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('status') } }


      sig { params(code: T.nilable(Float), message: T.nilable(String), status: T.nilable(Float)).void }
      def initialize(code: nil, message: nil, status: nil)
        @code = code
        @message = message
        @status = status
      end
    end

    # Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
    class UpdatePlayProgressResponseBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :errors, T.nilable(T::Array[Operations::UpdatePlayProgressErrors]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('errors') } }


      sig { params(errors: T.nilable(T::Array[Operations::UpdatePlayProgressErrors])).void }
      def initialize(errors: nil)
        @errors = errors
      end
    end


    class UpdatePlayProgressResponse < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, Faraday::Response
      # HTTP response status code for this operation
      field :status_code, Integer
      # Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
      field :object, T.nilable(Operations::UpdatePlayProgressResponseBody)


      sig { params(content_type: String, raw_response: Faraday::Response, status_code: Integer, object: T.nilable(Operations::UpdatePlayProgressResponseBody)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, object: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @object = object
      end
    end
  end
end
