# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module PlexRubySDK
  autoload :PlexAPI, 'plex_ruby_sdk/plex_api'
  autoload :ServerVariables, 'plex_ruby_sdk/server_variables'
  autoload :Shared, 'plex_ruby_sdk/models/shared'
  autoload :Operations, 'plex_ruby_sdk/models/operations'
  autoload :Server, 'plex_ruby_sdk/server'
  autoload :Media, 'plex_ruby_sdk/media'
  autoload :Video, 'plex_ruby_sdk/video'
  autoload :Activities, 'plex_ruby_sdk/activities'
  autoload :Butler, 'plex_ruby_sdk/butler'
  autoload :Plex, 'plex_ruby_sdk/plex'
  autoload :Hubs, 'plex_ruby_sdk/hubs'
  autoload :Search, 'plex_ruby_sdk/search'
  autoload :Library, 'plex_ruby_sdk/library'
  autoload :Watchlist, 'plex_ruby_sdk/watchlist'
  autoload :Log, 'plex_ruby_sdk/log'
  autoload :Playlists, 'plex_ruby_sdk/playlists'
  autoload :Authentication, 'plex_ruby_sdk/authentication'
  autoload :Statistics, 'plex_ruby_sdk/statistics'
  autoload :Sessions, 'plex_ruby_sdk/sessions'
  autoload :Updater, 'plex_ruby_sdk/updater'
  autoload :Users, 'plex_ruby_sdk/users'
end

require_relative 'plex_ruby_sdk/utils/t'
require_relative 'plex_ruby_sdk/utils/utils'
require_relative 'plex_ruby_sdk/utils/metadata_fields'
require_relative 'plex_ruby_sdk/sdkconfiguration'
