# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Download - Indicate that you want to start download any updates found.
    class Download < T::Enum
      enums do
        ZERO = new(0)
        ONE = new(1)
      end
    end

  end
end
