# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetBandwidthStatisticsDevice < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :client_identifier, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('clientIdentifier') } }

      field :created_at, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('createdAt') } }

      field :id, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }

      field :platform, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('platform') } }


      sig { params(client_identifier: T.nilable(::String), created_at: T.nilable(::Integer), id: T.nilable(::Integer), name: T.nilable(::String), platform: T.nilable(::String)).void }
      def initialize(client_identifier: nil, created_at: nil, id: nil, name: nil, platform: nil)
        @client_identifier = client_identifier
        @created_at = created_at
        @id = id
        @name = name
        @platform = platform
      end
    end
  end
end
