# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetDevicesMediaContainer < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :device, T.nilable(T::Array[::OpenApiSDK::Operations::Device]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Device') } }

      field :identifier, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('identifier') } }

      field :size, T.nilable(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('size') } }


      sig { params(device: T.nilable(T::Array[::OpenApiSDK::Operations::Device]), identifier: T.nilable(::String), size: T.nilable(::Float)).void }
      def initialize(device: nil, identifier: nil, size: nil)
        @device = device
        @identifier = identifier
        @size = size
      end
    end
  end
end
