# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetGlobalHubsMediaContainer < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :allow_sync, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('allowSync') } }

      field :hub, T.nilable(T::Array[::OpenApiSDK::Operations::Hub]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Hub') } }

      field :identifier, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('identifier') } }

      field :size, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('size') } }


      sig { params(allow_sync: T.nilable(T::Boolean), hub: T.nilable(T::Array[::OpenApiSDK::Operations::Hub]), identifier: T.nilable(::String), size: T.nilable(::Integer)).void }
      def initialize(allow_sync: nil, hub: nil, identifier: nil, size: nil)
        @allow_sync = allow_sync
        @hub = hub
        @identifier = identifier
        @size = size
      end
    end
  end
end
