# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetServerPreferencesMediaContainer < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :setting, T.nilable(T::Array[::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('Setting') } }

      field :size, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('size') } }


      sig { params(setting: T.nilable(T::Array[::Object]), size: T.nilable(::Integer)).void }
      def initialize(setting: nil, size: nil)
        @setting = setting
        @size = size
      end
    end
  end
end
