# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # IncludeDetails - Whether or not to include details for a section (types, filters, and sorts). 
    # Only exists for backwards compatibility, media providers other than the server libraries have it on always.
    # 
    class IncludeDetails < T::Enum
      enums do
        ZERO = new(0)
        ONE = new(1)
      end
    end

  end
end
