# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
    INCLUDE_COLLECTIONS_SERVERS = [
      'https://metadata.provider.plex.tv'
    ].freeze
  
    # IncludeCollections - include collections in the results
    # 
    class IncludeCollections < T::Enum
      enums do
        ONE = new(1)
        ZERO = new(0)
      end
    end

  end
end
