# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # PlaylistType - limit to a type of playlist.
    class PlaylistType < T::Enum
      enums do
        AUDIO = new('audio')
        VIDEO = new('video')
        PHOTO = new('photo')
      end
    end

  end
end
