# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class Provider < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :key, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('key') } }

      field :title, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('title') } }

      field :type, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('type') } }


      sig { params(key: T.nilable(::String), title: T.nilable(::String), type: T.nilable(::String)).void }
      def initialize(key: nil, title: nil, type: nil)
        @key = key
        @title = title
        @type = type
      end
    end
  end
end
