# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class Session < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :bandwidth, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('bandwidth') } }

      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :location, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('location') } }


      sig { params(bandwidth: T.nilable(::Integer), id: T.nilable(::String), location: T.nilable(::String)).void }
      def initialize(bandwidth: nil, id: nil, location: nil)
        @bandwidth = bandwidth
        @id = id
        @location = location
      end
    end
  end
end
