# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Smart - whether the playlist is smart or not
    class Smart < T::Enum
      enums do
        ZERO = new(0)
        ONE = new(1)
      end
    end

  end
end
