# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class StatisticsBandwidth < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :account_id, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('accountID') } }

      field :at, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('at') } }

      field :bytes, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('bytes') } }

      field :device_id, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('deviceID') } }

      field :lan, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('lan') } }

      field :timespan, T.nilable(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('timespan') } }


      sig { params(account_id: T.nilable(::Integer), at: T.nilable(::Integer), bytes: T.nilable(::Integer), device_id: T.nilable(::Integer), lan: T.nilable(T::Boolean), timespan: T.nilable(::Integer)).void }
      def initialize(account_id: nil, at: nil, bytes: nil, device_id: nil, lan: nil, timespan: nil)
        @account_id = account_id
        @at = at
        @bytes = bytes
        @device_id = device_id
        @lan = lan
        @timespan = timespan
      end
    end
  end
end
